version: '3'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_spring
    ports:
      - '3307:3306'
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: always
    ports:
      - '8686:8080'
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_DATABASE: library_spring
      MYSQL_USER: root
      MYSQL_PASSWORD: root