version: '3'

services:
  api:
    build: ./
    restart: always
    ports:
      - '8080:8080'
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test1
      MYSQL_USER: spring_learning
      MYSQL_PASSWORD: pass